sonar.projectKey=cobrixs-local
sonar.organization=geocarri-sudo
sonar.sources=src
sonar.exclusions=node_modules/**
sonar.sourceEncoding=UTF-8
sonar.host.url=https://sonarcloud.io
sonar.login=bbe3acd9882fbc5f3f66de24aa8f3f87b9504832